import type { Metadata } from 'next';

import '@/styles/globals.css';
import { firaCode } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={firaCode.className}>{children}</body>
    </html>
  );
}
